version: 2
updates:
  - package-ecosystem: "bun"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
